spring.application.name=preentrega-dylansalinas
spring.profiles.active=dev

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**
